server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://propel-assignment-hqu6.onrender.com;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
    }

   location /health {
    return 200 "OK";
    add_header Content-Type text/plain;
}

    location / {
        try_files $uri /index.html;
    }
}
